// The distilled short-story baseline master (from the earlier 6-round runs, best ~0.76-0.81). Pure data, no
// side effects, so any script can import it without triggering an experiment. The "prior tests baseline" a
// continued run starts from instead of a cold first-association draft.
export const BASELINE_MASTER = `A short story scores high only when its central idea is invented rather than recalled AND something actually happens: a model left alone returns the most-likely premise (lonely lighthouse keeper, message in a bottle, dying grandmother, last words, time-loop regret), which reads as cliche however clean the prose, and even an original conceit stalls at "clever tableau" when the protagonist makes no choice and pays no cost. This skill keeps CONVERGING on one winning skeleton (a forgotten trade or device wired to a dying/deathbed/last-words moment) because the master feeds top prior runs back to the writer; by the third reuse the skeleton IS the cliche, gets HARD-banned, and scores ~0.52, so a beautifully written deathbed story is a FAILURE. The plateau winners (~0.75) all build the thesis from outside material, put a LIVING character under present pressure who must DO something with a witnessed cost, and revise out every self-gloss, yet they stall just under masterwork because the convergence pull mutates: it stops being a banned premise and reappears as airless uniform prose, a symmetric closing MOTIF (a thematic word mirrored start-to-end, not just a mirrored image), a micro-gloss that names the relationship's shift, and a grounded conceit whose mechanism a knowledgeable reader can catch as false. Beating the plateau means killing those four mutations, not just the obvious cliche.

1. Research outside material before any prose: gather 3-5 specific real-world fragments (a current event, a historical detail, a technical fact, a concrete observed friction) that are NOT the obvious first associations of any premise.
2. Name the precise emotion those fragments raise, then connect at least two of them into a single earned, ironic controlling thesis. Test it against the pillow rule: if it could be cross-stitched on a pillow, push to its ironic dual that resists the cliche.
3. Output the gathered research and the chosen thesis explicitly, in a short note, before drafting. Do not write a line of story until this note exists.
4. Pressure-test the conceit's MECHANISM against how the real thing actually works: state, in the note, the one technical fact the story turns on and confirm it holds literally, so a domain-knowledgeable reader cannot catch the central device as false or as poetic license; if it does not hold, adjust the situation until it does.
5. Reject the first premise that comes to mind, and reject the skeleton this skill has reused: a death, a deathbed, a dying or mute person whose voice/last-words are the device, a forgotten-trade-plus-toxin setup, a lighthouse, a message in a bottle, a letter never sent, a last day on earth. Derive the situation from the grounded thesis instead.
6. Default the emotional engine to a LIVING, ongoing relationship under present-tense pressure rather than to death or mourning; choose a stake being decided now, outcome still open, not grieved.
7. Build the story around a turn, not a reveal: place a specific named character under pressure inside the grounded situation and force a choice, a cost, or an irreversible action witnessed by, hidden from, or paid against at least one other person. Never let the stake live only inside the protagonist's head, and never let the conceit be merely exposed as an ironic tableau.
8. Draft rendering the thesis through concrete action and specific particulars only. Never assert the moral, and cut any sentence that explains, names, or restates the meaning. This includes the subtle gloss that names what a relationship or act BECOMES (e.g. "the moment it turned into a partner's"): showing the gesture is enough; naming its significance is telling. The recurring trap is flagging such a line in self-critique and then rationalizing it as "just the procedure": delete it.
9. Vary sentence register deliberately: not every line may be an equally crafted, clause-loaded simile. Give each paragraph at least one short, plain, declarative sentence so the crafted lines land against breathing room. Uniform density reads as airless and blunts every image.
10. Do not button the ending with symmetry of any kind: not a mirrored final image, and not a repeated thematic MOTIF-WORD that bookends the piece (honesty, home, hands, light). Let the last beat sit off-center or unresolved; if a craft motif recurs, break its symmetry so it discovers rather than re-states.
11. Edit for AI tells: cap em-dashes at one or two, remove generic abstraction ("the silence," "the void," "enough"), break any rule-of-three cadence, collapse repeated anaphora to one, and replace predictable phrasing with sharper concrete language. Break the prose into paragraphs with a deliberate break at the turn so the decisive beat is not buried in a backstory block.
12. Send the finished draft to a subagent reviewer asked to judge (a) originality, (b) whether the premise reuses the banned death/deathbed/dying-voice skeleton, (c) whether the protagonist actually changes/decides/loses something against a witnessed cost, and (d) whether the central mechanism is literally plausible to a domain expert. Instruct it to flag for mandatory removal any cliche, trope, sentimentality, self-gloss or meaning-naming exposition (including relationship-naming), symmetric closing image OR motif-word, static-portrait stasis, internal-only stake, airless uniform-density passage, banned-skeleton premise, factually false conceit, or AI tell; revise against every flag before delivering.`;
